{% set name = "pocketsphinx-python" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/bambocher/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 09b784be9b683e3b7a37e0d2da00cd37c223a1ec5d5bb4df254498b5f6b64848
  - url: https://sourceforge.net/projects/cmusphinx/files/pocketsphinx/5prealpha/pocketsphinx-5prealpha.tar.gz
    sha256: ef5bb5547e2712bdf571f256490ef42a47962033892efd9d7df8eed7fe573ed9
    folder: deps/pocketsphinx
  - url: https://sourceforge.net/projects/cmusphinx/files/sphinxbase/5prealpha/sphinxbase-5prealpha.tar.gz
    sha256: f72bdb59e50b558bed47cc2105777200d2b246a0f328e913de16a9b22f9a246f
    folder: deps/sphinxbase

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - swig
    - automake
    - libtool
    - bison
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pocketsphinx

about:
  home: https://pypi.org/project/pocketsphinx/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pocketsphinx is a part of the CMU Sphinx Open Source Toolkit For Speech Recognition.

  description: |
    This package provides a python interface to CMU Sphinxbase and Pocketsphinx
    libraries created with SWIG and Setuptools.
  doc_url: https://pypi.org/project/pocketsphinx/
  dev_url: https://github.com/bambocher/pocketsphinx-python

extra:
  recipe-maintainers:
    - CurtLH
