travis:
  secure:
    BINSTAR_TOKEN: F//d3nz6QuPjXMWqsZu4m2sXssmZS98dru7ku+9k+nO3pR4asOqzgAKGWcyEdVYQGcmkWZBh0ZLL5Oi8qEoO+6hylCzjY2JUTzgbOJWZDyqU0yUK+RF9Gnc9rXj6pLhh41VZkv8+aiRSr3z7xhZJZgwWDx+L0WNcSx1GxiORRzJMGTSRpADQjqsVNtDXfVNQ8SIfEf60VBlbcA4lXqmHLyowmU/UR8hhk82jxwAtW9L3jf9Ve6NxDQ7quRTtHSHH9KZxMwmADn82a13DPlAxxcFEvflJNAIUzX+TUbYWBSgmBqsjqDL8nD0+4/vS6jyt99ZP6w7Voesj6RPO4BzeCtTxz6TI4b8oHYEjqf3IVTeOi/Q1Z8ya6iSgK1/YFEiSDZa+J/usrOuNdnDqKauRNo6JioCvE/+E/ZdCUh9w8LWMDbZd8LKkXpoDMrJ7aBpQXV1eCHl9NT28rsVPDZM6gyEACAKnvDD4OTzv8Kfc9P0H3gTcqkSVGEA+LtWLAyfMJUdwfL7pOdd8r/aqzqtL0uVm6asi9EI2x2lhygn1gsUzibLKK1Q3/qXZ/n08NbSXGsB9sCAjEG3NuYF85rU3OvNQLXFiZpxUX7RAWnC2rVRpsagApt2eex4+aK3rm7GVdPdsmnT/aOtABXgrJC15sqAVGl5cd+4SL4vzZeqdZ5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
